version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:80"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
